version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27117:27017
  api:
    image: 7b/project
    build: ../
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - mongo
    depends_on:
      - mongo